version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "33060:33060"
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  node:
    image: node
    ports:
      - "8080:8080"
